# Generated by Django 4.2.2 on 2023-10-18 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_logapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internapplications',
            name='contact',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplications',
            name='contact',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
