# Generated by Django 4.2.2 on 2023-11-03 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_logapp', '0002_alter_internapplications_contact_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internapplications',
            old_name='relocation',
            new_name='mode_of_work',
        ),
        migrations.RenameField(
            model_name='jobapplications',
            old_name='relocation',
            new_name='mode_of_work',
        ),
    ]
