# Generated by Django 4.2.2 on 2023-09-25 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_logapp', '0002_savedapplication_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savedapplication',
            options={'verbose_name': 'Savedapplication', 'verbose_name_plural': 'Savedapplication'},
        ),
        migrations.AlterField(
            model_name='savedapplication',
            name='internship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user_logapp.internships'),
        ),
        migrations.AlterField(
            model_name='savedapplication',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user_logapp.jobs'),
        ),
    ]
